import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>FotinhAI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Hello</h1>
      </main>
    </>
  );
}
