import Layout from '@/components/layout'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>FotinhAI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Hello</h1>
      </Layout>
    </>
  )
}
